node_types:
  - Person an TH Köln
  - Person extern
  - Studierende
  - Institut
  - Fakultät
  - Dekanat
  - DekanIn
  - Präsidium
  - Prüfungsausschussvorsitz
  - Prüfungsausschuss
  - InstitutsdirektorIn
  - Senat
  - Modul
  - Unternehmen
  - Forschungsprojekt
  - Prüfungsordnung
  - Studiengang
edge_types:
  - ist Modulverantwortlicher
  - ist Erstprüfer
  - ist Zweitprüfer
  - ist Element von
  - hat Funktion
  - schreibt Forschungsantrag
  - arbeitet in Forschungsprojekt
  - schreibt Bachelorarbeit
  - hat Bachelorarbeit angefragt
  - hat Bachelorarbeit abgeschlossen
  - schreibt Masterarbeit
  - hat Masterarbeit angefragt
  - hat Masterarbeit abgeschlossen
  - schreibt Projektarbeit
  - hat Projektarbeit angefragt
  - hat Projektarbeit abgeschlossen
  - hat Nachteilsausgleich beantragt
  - hat Nachteilsausgleich erhalten
  - hat PO-Wechsel beantragt
  - arbeitet in Unternehmen
  - macht Praxissemester
  - hat Praxissemester abgeschlossen
edge_priorities:
  Bachelorarbeit:
    - hat Bachelorarbeit angefragt
    - schreibt Bachelorarbeit
    - hat Bachelorarbeit abgeschlossen
  Masterarbeit:
    - hat Masterarbeit angefragt
    - schreibt Masterarbeit
    - hat Masterarbeit abgeschlossen
  Projektarbeit:
    - hat Projektarbeit angefragt
    - schreibt Projektarbeit
    - hat Projektarbeit abgeschlossen
  Forschungsprojekt:
    - schreibt Forschungsantrag
    - arbeitet in Forschungsprojekt
  Nachteilsausgleich:
    - hat Nachteilsausgleich beantragt
    - hat Nachteilsausgleich erhalten
  Praxissemester:
    - macht Praxissemester
    - hat Praxissemester abgeschlossen
