node_types:
  - Person
  - Modul
  - Unternehmen
edge_types:
  - lehrt
  - besucht
  - schreibt Bachelorarbeit
  - hat Bachelorarbeit angefragt
  - hat Bachelorarbeit abgeschlossen
  - schreibt Masterarbeit
  - hat Masterarbeit angefragt
  - hat Masterarbeit abgeschlossen
  - schreibt Projektarbeit
  - hat Projektarbeit angefragt
  - hat Projektarbeit abgeschlossen
  - hat Nachteilsausgleich beantragt
  - hat PO-Wechsel beantragt
edge_priorities:
  Bachelorarbeit:
    - hat Bachelorarbeit angefragt
    - schreibt Bachelorarbeit
    - hat Bachelorarbeit abgeschlossen
  Masterarbeit:
    - hat Masterarbeit angefragt
    - schreibt Masterarbeit
    - hat Masterarbeit abgeschlossen
  Projektarbeit:
    - hat Projektarbeit angefragt
    - schreibt Projektarbeit
    - hat Projektarbeit abgeschlossen
