name: Auto Versioning
on:
  push:
    branches: [ "main" ]
jobs:
  version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Auto Version and Badges
        uses: dgaida/auto-version-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
