name: Auto Versioning
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
on:
  push:
    branches: [ "master" ]
jobs:
  version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Auto Version and Badges
        uses: dgaida/auto-version-action@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
